#:schema node_modules/wrangler/config-schema.json
name = "trash-mania"
main = "src/index.ts"
compatibility_date = "2024-10-22"
compatibility_flags = ["nodejs_compat"]

assets = { directory = "./public", binding = "ASSETS" }

[[kv_namespaces]]
binding = "users"
id = "077c4594db364308a7fa24ee65657331"

# Workers Logs
# Docs: https://developers.cloudflare.com/workers/observability/logs/workers-logs/
# Configuration: https://developers.cloudflare.com/workers/observability/logs/workers-logs/#enable-workers-logs
[observability]
enabled = true
